#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=8
#SBATCH --job-name=LLC_plotting
#SBATCH --output=RunMethod_%A_h100_test_LLC_plotting.out
#SBATCH --time=12:00:00
#SBATCH --mem=40G
#SBATCH --hint=nomultithread

echo "✅ Job started at: $(date)"

# Load modules
module purge
module load 2023
module load Anaconda3/2023.07-2
module load CUDA/12.1.1

source activate devinterp_env



# python generate_comparison_plots.py --mode clean_vs_adv \
#     --experiment_dir ./llc_analysis/llc_analysis_20250819_094945/ResNet18_Standard_clean_vs_adv

python generate_comparison_plots.py --mode training_llc \
    --model_dir ./models/LeNet_Standard \
    --experiment_dir ./llc_analysis/llc_analysis_LeNet_Standard/LeNet_Standard_clean_vs_adv \
    --eff_dim_path ./eff_dim_analysis/batch_analysis_20250820_114823/LeNet_analysis/LeNet_Standard_effective_dim.json

python generate_comparison_plots.py --mode training_llc \
    --model_dir ./models/LeNet_AT \
    --experiment_dir ./llc_analysis/llc_analysis_LeNet_AT/LeNet_AT_clean_vs_adv \
    --eff_dim_path ./eff_dim_analysis/batch_analysis_20250820_114823/LeNet_analysis/LeNet_AT_effective_dim.json

python generate_comparison_plots.py --mode training_llc \
    --model_dir ./models/LeNet_TRADES \
    --experiment_dir ./llc_analysis/llc_analysis_LeNet_TRADES/LeNet_TRADES_clean_vs_adv \
    --eff_dim_path ./eff_dim_analysis/batch_analysis_20250820_114823/LeNet_analysis/LeNet_TRADES_effective_dim.json



# python generate_comparison_plots.py --mode training_llc \
#     --model_dir ./models/ResNet18_Standard_200 \
#     --experiment_dir ./llc_analysis/llc_analysis_ResNet18_Standard/ResNet18_Standard_clean_vs_adv 
#     # --eff_dim_path ./eff_dim_analysis/batch_analysis_20250820_114823/ResNet18_analysis/ResNet18_Standard_effective_dim.json

# python generate_comparison_plots.py --mode training_llc \
#     --model_dir ./models/ResNet18_AT_200 \
#     --experiment_dir ./llc_analysis/llc_analysis_ResNet18_AT/ResNet18_AT_clean_vs_adv 
#     # --eff_dim_path ./eff_dim_analysis/batch_analysis_20250820_114823/ResNet18_analysis/ResNet18_AT_effective_dim.json

# python generate_comparison_plots.py --mode training_llc \
#     --model_dir ./models/ResNet18_MART \
#     --experiment_dir ./llc_analysis/llc_analysis_ResNet18_MART/ResNet18_MART_clean_vs_adv 
#     # --eff_dim_path ./eff_dim_analysis/batch_analysis_20250820_114823/ResNet18_analysis/ResNet18_MART_effective_dim.json

# python generate_comparison_plots.py --mode training_llc \
#     --model_dir ./models/ResNet18_AT_AWP \
#     --experiment_dir ./llc_analysis/llc_analysis_ResNet18_ATAWP/ResNet18_ATAWP_clean_vs_adv 
#     # --eff_dim_path ./eff_dim_analysis/batch_analysis_20250820_114823/ResNet18_analysis/ResNet18_AT_AWP_effective_dim.json









# python generate_comparison_plots.py --mode defense_comparison \
#     --experiment_dirs \
#         ./llc_analysis/llc_analysis_ResNet18_Standard/ResNet18_Standard_clean_vs_adv \
#         ./llc_analysis/llc_analysis_ResNet18_AT/ResNet18_AT_clean_vs_adv \
#         ./llc_analysis/llc_analysis_ResNet18_MART/ResNet18_MART_clean_vs_adv \
#         ./llc_analysis/llc_analysis_ResNet18_ATAWP/ResNet18_ATAWP_clean_vs_adv \
#     --dataset CIFAR10 \
#     --output_name ResNet18_defense_methods_comparison_updated


# python generate_comparison_plots.py --mode defense_comparison \
#     --experiment_dirs \
#         ./llc_analysis/llc_analysis_LeNet_Standard/LeNet_Standard_clean_vs_adv \
#         ./llc_analysis/llc_analysis_LeNet_AT/LeNet_AT_clean_vs_adv \
#         ./llc_analysis/llc_analysis_LeNet_TRADES/LeNet_TRADES_clean_vs_adv \
#     --dataset MNIST \
#     --output_name LeNet_defense_methods_comparison_updated